    version: "3"
    services:
        db:
            container_name: postgres
            image: postgres
            restart: always
            environment:
                POSTGRES_PASSWORD: ""
                POSTGRES_HOST_AUTH_METHOD: "trust"
            ports:
                - 5432:5432
            volumes:
                - ./volumes/PostgreSQL:/var/lib/postgresql/data

        pgadmin:
            restart: always
            container_name: pgadmin4
            image: dpage/pgadmin4
            environment:
                PGADMIN_DEFAULT_EMAIL: "uilton@ifro.com"
                PGADMIN_DEFAULT_PASSWORD: "123456"
            ports:
                - "80:80"
            volumes:
                - ./volumes/pgadmin:/var/lib/pgadmin/storage/
            depends_on:
                - db

        mailhog:
            container_name: mailhog
            image: mailhog/mailhog
            restart: always
            logging:
              driver: 'none'  # disable saving logs
            ports:
              - 1025:1025 # smtp server
              - 8025:8025 # web ui
