    version: "3"
    services:
        db:
            container_name: postgres
            image: postgres:16-alpine
            restart: always
            environment:
                POSTGRES_USER: "postgres"
                POSTGRES_PASSWORD: "123"
                # POSTGRES_HOST_AUTH_METHOD: "trust"
                TZ: "America/Porto_Velho"
            ports:
                - 5432:5432
            volumes:
                - ./volumes/PostgreSQL:/var/lib/postgresql/data

        mail:
            container_name: mailhog
            image: mailhog/mailhog
            restart: always
            logging:
              driver: 'none'  # disable saving logs
            ports:
              - 1025:1025 # smtp server
              - 8025:8025 # web ui
